name: Build and push

on:
  push:
    branches: [test]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/aspnet-app
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG app/aspnetapp/
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
